kind: Service
apiVersion: v1
metadata:
  name: example-service-test
  namespace: test
  labels:
    app: example-service-test
spec:
  selector:
    app: example-service-test
  ports:
  - name: web
    port: 8080
    nodePort: 30901
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-service-test
  namespace: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-service-test
    spec:
      containers:
      - name: example-service-test
        image: xienokia/hello-app
        ports:
        - name: web
          containerPort: 8080